
name: Run packer build on a template file
on:
  push:
    branches:
        - 'main'
jobs:
  packer_build:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v2
      - run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - 
      - run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - run: sudo apt-get update && sudo apt-get install packer
      - run: packer validate ami.json    
      - run: packer build ami.json
        env:
         AMI_USERS: ${{secrets.AMI_USERS}}
         AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
         AWS_REGION: ${{secrets.AWS_REGION}}
         AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
         SOURCE_AMI: "ami-0817d428a6fb68645"
         SSH_USERNAME: ${{secrets.SSH_USERNAME}}
     


         
